version: '3.8'

volumes:
  grafana-data:
  prometheus-data: 

services:
  nginx:
    build: /nginx
    container_name: nginx_park
    ports:
      - "80:80"
    depends_on:
      - api_1
      - api_2
      - api_3
  api_1:
    build: /api
    container_name: container_apiPark_1
    ports:
      - "8080:8000"
      - "9104:9100"
  api_2:
    build: /api
    container_name: container_apiPark_2
    ports:
      - "8081:8000"
      - "9101:9100"
      # - "9091:9090"
  api_3:
    build: /api
    container_name: container_apiPark_3
    ports:
      - "8082:8000"
      - "9103:9100"
      # - "9092:9090"
  grafana:
    image: grafana/grafana:latest
    container_name: container_grafana
    restart: unless-stopped
    ports:
      - "8083:3000"
    # environment:
      # - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource
    volumes: 
      - ./grafana-s:/var/lib/grafana
  prometheus:
    image: prom/prometheus:latest
    container_name: container_prometheus
    restart: unless-stopped
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-data:/prometheus
    ports:
    - 8084:9090
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention.time=2d'
    - '--web.enable-lifecycle'
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    