global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'container_prometheus'
    static_configs:
    - targets: ['container_prometheus:9090']
    
  - job_name: 'container_apiPark_1'
    static_configs:
    - targets: ['container_apiPark_1:8000']
  
  - job_name: 'node-exporter_apiPark_1'
    static_configs:
    - targets: ['container_apiPark_1:9100']

  - job_name: 'container_apiPark_2'
    static_configs:
    - targets: ['container_apiPark_2:8000']

  - job_name: 'node-exporter_apiPark_2'
  static_configs:
  - targets: ['container_apiPark_2:9100']      

  - job_name: 'container_apiPark_3'
    static_configs:
    - targets: ['container_apiPark_3:8000']

  - job_name: 'node-exporter_apiPark_3'
  static_configs:
  - targets: ['container_apiPark_3:9100']
     
    #metrics_path: '/metrics'
    #metrics_path: '/prometheus'